import re

_YEAR: str
_MONTH: str
_DAY: str
_DAY_LOOSE: str
_MONTH_NAMES: str
_COMPACT_YEAR_FIRST: re.Pattern[str]
_COMPACT_YEAR_LAST: re.Pattern[str]
_FUSED_NAMED_DATE: re.Pattern[str]
_YEAR_PIECE: re.Pattern[str]
_MONTH_PIECE: re.Pattern[str]
_DAY_PIECE: re.Pattern[str]
_DAY_LOOSE_PIECE: re.Pattern[str]
_TWO_DIGIT_PIECE: re.Pattern[str]
_MONTH_NAME_PIECE: re.Pattern[str]

def group_videos(videos: list[str], group_by_pattern: str | None = None) -> dict[str, list[str]]: ...
def _infer_group_key(stem: str) -> str | None: ...
def _find_date_span(pieces: list[str]) -> tuple[int, int] | None: ...
def _is_month_day_pair(first: str, second: str) -> bool: ...
def _is_numeric_date_triple(trio: tuple[str, str, str]) -> bool: ...
def _is_named_date_triple(trio: tuple[str, str, str]) -> bool: ...
def _is_day_piece(piece: str) -> bool: ...
def _is_year_piece(piece: str) -> bool: ...
def _is_named_month_year_pair(first: str, second: str) -> bool: ...
def _is_compact_date_piece(piece: str) -> bool: ...
def _is_fused_named_date_piece(piece: str) -> bool: ...
