from typing import Any, TextIO

from _typeshed import Incomplete
from deeplabcut.pose_estimation_pytorch.runners.logger import BaseLogger

from ..reporting import (
    LiveBar as LiveBar,
    format_duration as format_duration,
)

_MAX_RENDERED_METRICS: int
_RENDERED_METRIC_PREFIXES: tuple[str, ...]

class QueueTrainingLogger(BaseLogger):
    _progress_queue: Incomplete
    _task_name: Incomplete
    def __init__(self, progress_queue: Any, task_name: str = "pose") -> None: ...
    def log_config(self, config: dict | None = None) -> None: ...
    def log(self, metrics: dict[str, Any], step: int | None = None) -> None: ...
    def save(self) -> None: ...
    def _put(self, message: dict[str, Any]) -> None: ...

class TrainingMonitor(LiveBar):
    _total_epochs: int
    _task: str
    _current_epoch: int
    _training_loss: float | None
    _validation_loss: float | None
    _metrics: dict[str, Any]
    def __init__(self, progress_queue: Any, stream: TextIO | None = None) -> None: ...
    def __repr__(self) -> str: ...
    def _ingest(self, message: Any) -> bool: ...
    def _is_preparing(self) -> bool: ...
    def _ingest_metrics(self, message: dict[str, Any]) -> None: ...
    def _format_metrics(self) -> str: ...
    def _compose_active(self, elapsed: float) -> str: ...
